apiVersion: v1
kind: Pod
metadata:
  name: curltest
  namespace: default
spec:
  containers:
  - name: curltest
    image: radial/busyboxplus:curl 
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
